"""create menu table

Revision ID: 650e9c0da335
Revises: 9083ab78db41
Create Date: 2026-02-26 08:57:43.689953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "650e9c0da335"
down_revision: Union[str, Sequence[str], None] = "9083ab78db41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu",
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "calorie_target", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "menu_structure", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("daily_kcal_estimates", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menu_product",
        sa.Column("menu_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("unit", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_menu_product_quantity_gt_0"),
        sa.ForeignKeyConstraint(["menu_id"], ["menu.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("menu_id", "product_id", name="uq_menu_product"),
    )
    op.create_index(
        op.f("ix_menu_product_menu_id"), "menu_product", ["menu_id"], unique=False
    )
    op.create_index(
        op.f("ix_menu_product_product_id"), "menu_product", ["product_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_menu_product_product_id"), table_name="menu_product")
    op.drop_index(op.f("ix_menu_product_menu_id"), table_name="menu_product")
    op.drop_table("menu_product")
    op.drop_table("menu")
    # ### end Alembic commands ###
