"""create product and its type

Revision ID: 9083ab78db41
Revises:
Create Date: 2026-02-02 13:43:55.892784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import insert as pg_insert

from receptor.core.domain.product_categories import ProductTypeCode

# revision identifiers, used by Alembic.
revision: str = "9083ab78db41"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_type",
        sa.Column("code", sa.String(), primary_key=True),
        sa.Column("name_ru", sa.String(128), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "product",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type_code", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("calories_per_unit", sa.SmallInteger(), nullable=False),
        sa.Column("price_rub", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["type_code"],
            ["product_type.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_type_id"), "product", ["type_code"], unique=False)
    # --- seed product_type (idempotent)
    bind = op.get_bind()

    product_type_tbl = sa.table(
        "product_type",
        sa.column("code", sa.String),
        sa.column("name_ru", sa.String),
    )

    rows = [{"code": c.code, "name_ru": c.name_ru} for c in ProductTypeCode]

    stmt = (
        pg_insert(product_type_tbl)
        .values(rows)
        .on_conflict_do_update(
            index_elements=["code"],
            set_={"name_ru": pg_insert(product_type_tbl).excluded.name_ru},
        )
    )

    bind.execute(stmt)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_type_id"), table_name="product")
    op.drop_table("product")
    op.drop_table("product_type")
    # ### end Alembic commands ###
